### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by MetaMemoryT** [robenkleene/toggle-packages#3]
```
TypeError: undefined is not a function
  at toggle-packages.TogglePackagesStatusView.attach (c:\Users\Sean\.atom\packages\toggle-packages\lib\toggle-packages-status-view.coffee:19:34)
  at c:\Users\Sean\.atom\packages\toggle-packages\lib\toggle-packages-status-view.coffee:24:10
  at Emitter.module.exports.Emitter.emit (c:\ProgramData\chocolatey\lib\Atom.0.155.0\tools\Atom\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.activate (c:\ProgramData\chocolatey\lib\Atom.0.155.0\tools\Atom\resources\app\src\package-manager.js:382:27)
  at Atom.module.exports.Atom.startEditorWindow (c:\ProgramData\chocolatey\lib\Atom.0.155.0\tools\Atom\resources\app\src\atom.js:601:21)
  at Object.<anonymous> (c:\ProgramData\chocolatey\lib\Atom.0.155.0\tools\Atom\resources\app\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (c:\ProgramData\chocolatey\lib\Atom.0.155.0\tools\Atom\resources\app\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (c:\ProgramData\chocolatey\lib\Atom.0.155.0\tools\Atom\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///C:/ProgramData/chocolatey/lib/Atom.0.155.0/tools/Atom/resources/app/static/index.js:59:25)
 index.js:73window.onload
```

**Comment by robenkleene** [comment]
Hi MetaMemoryT, correct my if I'm wrong but it looks like you're using an older version of Atom (0.155.0, the current version is 0.184.0). If you are experiencing this issue in the latest version of Atom then please reopen it. Thanks! -Roben
